from .auto_editor import NODE_CLASS_MAPPINGS as AE_NODES, NODE_DISPLAY_NAME_MAPPINGS as AE_NAMES
from .audio_mixer import NODE_CLASS_MAPPINGS as AM_NODES, NODE_DISPLAY_NAME_MAPPINGS as AM_NAMES

NODE_CLASS_MAPPINGS = {**AE_NODES, **AM_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**AE_NAMES, **AM_NAMES}
